[ {
"url":"https://pbs.twimg.com/media/Ff43ozRXwAE_URH?format=jpg&name=medium",
"title":"Лукизм",
"info":"Пак Хен-сок-мектепте үнемі қорлық көретін семіз әрі ұсқынсыз орта мектеп оқушысы. Бірде, ол ұйықтаса әдемі денеге ауысатын қабілетке ие болады.Кейін...",
"jp":"Lookism",
"country":"Оңтүстік Корея, 8 желтоқсан 2022ж",
"info1":"8 эп. ~25мин",
"info2":"Көп бөлімді, шықты",
"info3":"Студия Studio Mir, автор Тхэчжун Пак",
"description":"Экшен, комедия, драма, тылсым күштер",
"note":"Ескертулер жоқ!",
"age":"16+",
"language":"Орыс тілінде",
"hd":"720p",
"moderator":"null",
"cause":"null",
"data_delete":"null",
"block":"null",
"note_li":"null",
"unavailable":"null",
"sl":"lookism-sl"
} ]
