[ {
"url":"https://unel-app.github.io/api.unel.tv/web-server/image/Ruler-Master-of-the-Mas.png",
"title":"Бетберденің иесі",
"info":"Белгісіз",
"jp":"군주-가면의 주인",
"country":"Оңтүстік Корея, 10 мамыр 2017ж",
"info1":"20 эп. ~59мин",
"info2":"Сериал, толығымен шықты",
"info3":"Студия ???, автор ???",
"description":"Тарихи, Дорама",
"note":"Ескертулер жоқ!😊",
"age":"16+",
"language":"Қазақ тілінде",
"hd":"380p, 480p",
"moderator":"null",
"cause":"null",
"data_delete":"null",
"block":"null",
"note_li":"null",
"unavailable":"null",
"sl":"the-emperor-owner-of-the-mask-sl"
} ]
